//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UAVtest.rc
//
#define IDD_UAVTEST_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDB_HORIZON_MSK                 129
#define IDB_HORIZON                     130
#define IDB_HORIZON_PITCH               131
#define IDB_HORIZON_MSK2                133
#define IDB_COMPAS                      134
#define IDB_COMPAS_MSK                  135
#define IDB_ALT                         136
#define IDB_ALT_MSK                     137
#define IDB_VAR                         138
#define IDB_VAR_MSK                     139
#define IDB_SPEED                       140
#define IDB_SPEED_MSK                   141
#define IDD_CONFIG                      142
#define IDD_APCONTROL                   143
#define IDD_ROUTE                       143
#define IDD_JOYCFG                      144
#define IDD_ADSCALIBRATE                146
#define IDD_ADSSET                      146
#define IDR_MENU1                       147
#define IDC_PORT                        1000
#define IDC_RATE                        1001
#define IDC_BTNCONNECT                  1002
#define IDC_TIMESTAMP                   1003
#define IDC_FLAGS                       1004
#define IDC_INS_PITCH                   1005
#define IDC_INS_ROLL                    1006
#define IDC_INS_YAW                     1007
#define IDC_INS_PITCHSPEED              1008
#define IDC_NSAT                        1008
#define IDC_INS_ROLLSPEED               1009
#define IDC_INS_YAWSPEED                1010
#define IDC_ADS_INDSPEED                1011
#define IDC_ADS_AIRSPEED                1012
#define IDC_ADS_BAROALT                 1013
#define IDC_ADS_PRESSURE                1014
#define IDC_AUX_DIRECTALT               1014
#define IDC_ADS_VSPEED                  1015
#define IDC_ADS_INDSPEED2               1016
#define IDC_INS_YAW2                    1017
#define IDC_INFO                        1018
#define IDC_SPL1UIN                     1019
#define IDC_STATE                       1019
#define IDC_RECVERR                     1020
#define IDC_SPL1UOUT                    1021
#define IDC_RECVERR2                    1021
#define IDC_ADDR                        1021
#define IDC_GPS_LATITUDE                1022
#define IDC_GPS_LONGITUDE               1023
#define IDC_GPS_ALTITUDE                1024
#define IDC_GPS_UTCTIME                 1025
#define IDC_ENG_RPM                     1026
#define IDC_ENG_TEMP1                   1027
#define IDC_ENG_TEMP2                   1028
#define IDC_AVIAHORIZON                 1029
#define IDC_COMPAS                      1030
#define IDC_ALT                         1031
#define IDC_VAR                         1032
#define IDC_SPEED                       1033
#define IDC_HDGSRC                      1034
#define IDC_SPDSRC                      1035
#define IDC_ALTSRC                      1036
#define IDC_SLIDER_THROTTLE             1037
#define IDC_SLIDER_AILERONS             1038
#define IDC_SLIDER_ELEVATOR             1039
#define IDC_SLIDER_RUDDER               1040
#define IDC_CMBFLAPS                    1041
#define IDC_CHKPARACHUTE                1042
#define IDC_ENG_FUELLEVEL               1042
#define IDC_CHKIGNITION                 1043
#define IDC_CMBMODE                     1044
#define IDC_SERVOU                      1044
#define IDC_BTNMODE                     1045
#define IDC_SERVOI                      1045
#define IDC_DEBUG                       1046
#define IDC_CONTROL                     1046
#define IDC_DEBUG2                      1047
#define IDC_TRACK                       1047
#define IDC_SPL1ILOAD                   1048
#define IDC_SPL1IBAT                    1049
#define IDC_SPL1FLAGS                   1050
#define IDC_SPL2UIN                     1051
#define IDC_SPL2UOUT                    1052
#define IDC_SPL2ILOAD                   1053
#define IDC_SPL2IBAT                    1054
#define IDC_SPL2FLAGS                   1055
#define IDC_SPL3UIN                     1056
#define IDC_SPL3UOUT                    1057
#define IDC_SPL3ILOAD                   1058
#define IDC_SPL3IBAT                    1059
#define IDC_SPL3FLAGS                   1060
#define IDC_SPL4UIN                     1061
#define IDC_SPL4UOUT                    1062
#define IDC_SPL4ILOAD                   1063
#define IDC_SPL4IBAT                    1064
#define IDC_SPL4FLAGS                   1065
#define IDC_CHKOISENABLE                1066
#define IDC_OISSTATUS                   1067
#define IDC_BTNREAD                     1070
#define IDC_CHKLOCK                     1070
#define IDC_BTNWRITE                    1071
#define IDC_BTNSETWPT                   1072
#define IDC_BTNGOTOWPT                  1073
#define IDC_EDTIME                      1076
#define IDC_EDAIRSPEED                  1077
#define IDC_BTNCONFIG                   1090
#define IDC_BTNAPCONTROL                1091
#define IDC_BTNROUTE                    1091
#define IDC_BTNJOYCONFIG                1092
#define IDC_LISTWPT                     1093
#define IDC_BTNADSRESET                 1093
#define IDC_EDALT                       1094
#define IDC_BTNADSCALIBRATE             1094
#define IDC_EDLON                       1095
#define IDC_BTNOISLEFT                  1095
#define IDC_EDLAT                       1096
#define IDC_BTNOISRIGHT                 1096
#define IDC_EDNUM                       1097
#define IDC_BTNOISUP                    1097
#define IDC_BTNLOADKML                  1098
#define IDC_BTNOISDOWN                  1098
#define IDC_BTNSAVEKML                  1099
#define IDC_BTNOISZOOMIN                1099
#define IDC_CMBJOY                      1100
#define IDC_BTNOISZOOMOUT               1100
#define IDC_CMBAILERONS                 1101
#define IDC_PRGAILERONS                 1102
#define IDC_CMBELEVATOR                 1103
#define IDC_PRGELEVATOR                 1104
#define IDC_CMBRUDDER                   1105
#define IDC_PRGRUDDER                   1106
#define IDC_CMBTHROTTLE                 1107
#define IDC_PRGTHROTTLE                 1108
#define IDC_CHKAILERONS                 1109
#define IDC_CHKELEVATOR                 1110
#define IDC_CHKRUDDER                   1111
#define IDC_CHKTHROTTLE                 1112
#define IDC_CMBFLAPS0                   1113
#define IDC_EDFLAPS0                    1114
#define IDC_CMBFLAPS1                   1115
#define IDC_EDFLAPS1                    1116
#define IDC_CMBTYPE                     1116
#define IDC_CMBFLAPS2                   1117
#define IDC_EDFLAPS2                    1118
#define IDC_CMBPARACHUTE                1119
#define IDC_CMBOISLOCK                  1119
#define IDC_EDPARACHUTE                 1120
#define IDC_EDOISLOCK                   1120
#define IDC_CMBIGNITION                 1121
#define IDC_CMBOISIR                    1121
#define IDC_EDIGNITION                  1122
#define IDC_EDOISIR                     1122
#define IDC_CMBTRIMU                    1123
#define IDC_BTNLOAD                     1124
#define IDC_EDTRIMU                     1124
#define IDC_CMBTRIMD                    1125
#define IDC_BTNSAVE                     1126
#define IDC_EDTRIMD                     1126
#define IDC_CMBTRIML                    1127
#define IDC_EDTRIML                     1128
#define IDC_CMBTRIMR                    1129
#define IDC_EDTRIMR                     1130
#define IDC_EDTRIMTO                    1131
#define IDC_EDDEADZONE                  1131
#define IDC_EDTRIMLND                   1132
#define IDC_CHKTELEMATIKA               1132
#define IDC_TREE1                       1133
#define IDC_OISSTATE                    1133
#define IDC_LIST1                       1134
#define IDC_EDIT1                       1135
#define IDC_EDTEMP                      1137
#define IDC_EDPRESSURE                  1138
#define IDC_CMBVALUE                    1139
#define IDC_LISTPOWERMODULES            1140
#define IDC_LISTFAILURES                1141
#define IDC_PROGRESS1                   1141
#define IDC_PARAMPROGRESS               1141
#define IDC_LISTSNLEVELS                1142
#define ID_DATA_CONFIG                  32771
#define ID_DATA_ROUTE                   32772
#define ID_COMMAND_AUTO                 32773
#define ID_COMMAND_ENGSTART             32774
#define ID_COMMAND_TAKEOFFSTART         32775
#define ID_COMMAND_ABORT                32776
#define ID_COMMAND_EMERGENCY            32777
#define ID_ADS_RESET                    32778
#define ID_ADS_SETNULLPOINT             32779
#define ID_WINDOW_JOYSTICKCONFIG        32780
#define ID_COMMAND_FUTABA               32781
#define ID_COMMAND_FUTABA32782          32782
#define ID_COMMAND_FUTABA32783          32783
#define ID_COMMAND_MANUAL               32784
#define ID_COMMAND_FUTABA32785          32785
#define ID_COMMAND_TAKEOFF              32786
#define ID_WINDOW_CONFIG                32787
#define ID_WINDOW_ROUTE                 32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1142
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
